# DNS Server Listen Address
listen: 0.0.0.0:53

# One or more DNS Upstream Servers (default: Google DNS)
upstream:
  - 8.8.8.8:53
  - 8.8.4.4:53

# One or more Blacklist sources
blacklist:
  - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

# Blacklist renewal interval in minutes - set to 0 to disable
blacklistRenewal: 1440

# You can also choose to blacklist everything (only whitelist will work then)
blacklistEverything: false

# Domain names to be resolved upstream, even if they are blacklisted
# Domains in blacklist and whitelist can begin with wildcard followed by star:
# Pattern "*.example.com" allows all of the following:
# - example.com
# - subdoman.example.com
# - deep.subdomain.example.com
#
# The star can only appear as a prefix and must be immediately followed by
# a dot. You must use quotes in yaml to use the wildcard
whitelist:
  - googleadservices.com
  - iadsdk.apple.com
  - "*.google.com"

# Optional names to be resolved to specific IP addresses
local:
  - name: service1.local
    target:
    - address: 192.168.178.1
      type: A
    - address: 192.168.179.1
      type: A
    - address: fe80::9656:d028:8652:1111
      type: AAAA
  - name: service2.local
    target:
    - address: 192.168.178.2
      type: A
