VERSION=`cat ./VERSION | awk NF`

all: clean update_version_file linux

clean:
	rm -f build/*

update_version_file:
	echo "// File autogenerated from VERSION, do not change manually!\npackage main\n\nconst AppVersion = \"${VERSION}\"" > src/version.go

linux: linux_amd64 linux_arm64 linux_arm

linux_amd64:
	env GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o build/sleuth_linux_amd64_${VERSION} src/*.go

linux_arm64:
	env GOOS=linux GOARCH=arm64 go build -ldflags="-w -s" -o build/sleuth_linux_arm64_${VERSION} src/*.go

linux_arm:
	env GOOS=linux GOARCH=arm go build -ldflags="-w -s" -o build/sleuth_linux_arm_${VERSION} src/*.go


init:
	npm install
	go mod vendor