name: Run Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:

  container-job:
    runs-on: ubuntu-latest
    container: golang:1.24-alpine
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      working-directory: src
      run: go test -cover -v
      env:
        CGO_ENABLED: 0